---
- name: Crear el volumen de datos para Portainer
  community.docker.docker_volume:
    name: portainer_data

- name: Arrancar el contenedor de Portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:lts
    pull: always
    state: started
    restart_policy: unless-stopped
    published_ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
