- name: Descargar la clave de firma de paquetes de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Obtener la arquitectura del sistema
  ansible.builtin.command: dpkg --print-architecture
  register: arquitectura

- name: Añadir el repositorio apt para la versión estable
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ arquitectura.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} stable
    state: present

- name: Actualizar el índice de paquetes
  ansible.builtin.apt:
    update_cache: true

- name: Instalar Docker y sus dependencias
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Arrancar el servicio Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Añadir el usuario debian al grupo docker
  ansible.builtin.user:
    name: debian
    groups: docker
    append: yes
